package dev.gomoku.rapfidroid.data.explorer

import dev.gomoku.rapfidroid.core.model.RjGame
import dev.gomoku.rapfidroid.core.model.RjNext
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Readers for `renju_stats.pack` / `renju_games.pack` — the opening explorer's
 * offline data, generated by `rifdb/rif_pack.py` (**its docstring is the format
 * spec**; `rif_packread.py` is the reference reader and `main.c:4771-4966` the
 * shipped C one this mirrors).
 *
 * ⚠ **Licence**: the packs are derived from the RenjuNet game database, which
 * allows *offline non-commercial use only*. They are therefore **never bundled
 * with the app and never exported** — the user builds them from their own `.rif`
 * download and imports them through the Storage Access Framework, exactly as the
 * desktop expects them next to `Yixin.exe`.
 *
 * Every offset and length is bounds-checked: a truncated or tampered pack
 * degrades to "no statistics", never to a crash.
 */

/**
 * A position record. The game-id list of the empty-board key holds every game
 * in the database, so ids are read on demand instead of being materialised.
 */
class RjStat internal constructor(
    private val buf: ByteBuffer,
    val games: Int,
    val blackWins: Int,
    val draws: Int,
    val whiteWins: Int,
    private val nextOff: Int,
    val nextCount: Int,
    private val gamesOff: Int,
    val gameCount: Int,
) {
    fun nextMoves(): List<RjNext> = (0 until nextCount).map { i ->
        val p = nextOff + 18 * i
        RjNext(
            x = buf.get(p).toInt() and 0xff,
            y = buf.get(p + 1).toInt() and 0xff,
            games = buf.getInt(p + 2),
            blackWins = buf.getInt(p + 6),
            draws = buf.getInt(p + 10),
            whiteWins = buf.getInt(p + 14),
        )
    }

    fun gameIdAt(index: Int): Int = buf.getInt(gamesOff + 4 * index)
}

/** `renju_stats.pack` — FNV-1a 64 hash index, linear probing, key confirmed
 *  against the stored string (the C reader's discipline, kept verbatim). */
class RjStatsPack private constructor(private val buf: ByteBuffer) {

    private val nslots = buf.getInt(12)
    private val recBase = 64 + 12L * nslots

    val positions: Int = buf.getInt(8)
    val totalGames: Int = buf.getInt(16)
    val maxPlies: Int = buf.getInt(20)
    val minGames: Int = buf.getInt(24)
    /** Build date as `YYYYMMDD`. */
    val date: Int = buf.getInt(28)

    fun lookup(key: String): RjStat? {
        if (nslots <= 0 || nslots and (nslots - 1) != 0) return null
        val keyBytes = key.toByteArray(Charsets.US_ASCII)
        val h = fnv1a64(keyBytes)
        val mask = nslots - 1
        var s = (h and mask.toLong()).toInt()
        // The table is built at 70 % load, so a free slot always ends the probe.
        // The trip count is bounded anyway: a corrupted pack with no empty slot
        // must fail the lookup, not spin.
        repeat(nslots) {
            val slot = 64 + 12 * s
            if (slot + 12 > buf.capacity()) return null
            val off = buf.getInt(slot + 8).toLong() and 0xffffffffL
            if (off == 0L) return null
            val stored = (buf.getInt(slot).toLong() and 0xffffffffL) or
                (buf.getInt(slot + 4).toLong() shl 32)
            if (stored == h) read(recBase + off, keyBytes)?.let { return it }
            s = (s + 1) and mask
        }
        return null
    }

    private fun read(at: Long, keyBytes: ByteArray): RjStat? {
        val cap = buf.capacity().toLong()
        if (at < 0 || at + 2 > cap) return null
        var p = at.toInt()
        val klen = buf.getShort(p).toInt() and 0xffff
        if (klen != keyBytes.size || at + 2 + klen + 18 > cap) return null
        for (i in 0 until klen) if (buf.get(p + 2 + i) != keyBytes[i]) return null
        p += 2 + klen
        val n = buf.getInt(p)
        val bw = buf.getInt(p + 4)
        val dw = buf.getInt(p + 8)
        val ww = buf.getInt(p + 12)
        val nnext = buf.get(p + 16).toInt() and 0xff
        val nextOff = p + 17
        val after = nextOff.toLong() + 18L * nnext
        if (after + 4 > cap) return null
        val ngames = buf.getInt(after.toInt())
        if (ngames < 0 || after + 4 + 4L * ngames > cap) return null
        return RjStat(buf, n, bw, dw, ww, nextOff, nnext, after.toInt() + 4, ngames)
    }

    companion object {
        const val MAGIC = "RJS1"

        /** Validates magic and version; returns null on anything unexpected. */
        fun open(source: ByteBuffer): RjStatsPack? {
            val buf = source.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            if (buf.capacity() < 64) return null
            if (magic(buf) != MAGIC || buf.getInt(4) != 2) return null
            return RjStatsPack(buf)
        }

        fun fnv1a64(data: ByteArray): Long {
            var h = -0x340d631b7bdddcdbL   // 0xcbf29ce484222325
            for (b in data) {
                h = h xor (b.toLong() and 0xff)
                h *= 0x100000001b3L
            }
            return h
        }

        fun fnv1a64(s: String): Long = fnv1a64(s.toByteArray(Charsets.US_ASCII))
    }
}

/** `renju_games.pack` — id-sorted index with binary search + a shared string
 *  pool. */
class RjGamesPack private constructor(private val buf: ByteBuffer) {

    private val idxOff = buf.getInt(16)
    private val openTblOff = buf.getInt(20)
    private val ruleTblOff = buf.getInt(24)
    private val poolOff = buf.getInt(28)

    val gameCount: Int = buf.getInt(8)

    fun game(id: Int): RjGame? {
        var lo = 0
        var hi = gameCount - 1
        while (lo <= hi) {
            val mid = (lo + hi) / 2
            val e = idxOff + 8 * mid
            if (e + 8 > buf.capacity()) return null
            val cid = buf.getInt(e)
            if (cid == id) return read(buf.getInt(e + 4))
            if (uLess(cid, id)) lo = mid + 1 else hi = mid - 1
        }
        return null
    }

    private fun read(at: Int): RjGame? {
        if (at < 0 || at + 59 > buf.capacity()) return null
        val nmoves = buf.get(at + 58).toInt() and 0xff
        if (at + 59 + nmoves > buf.capacity()) return null
        return RjGame(
            id = buf.getInt(at),
            year = buf.getShort(at + 4).toInt() and 0xffff,
            result = buf.get(at + 6).toInt() and 0xff,
            rule = buf.get(at + 7).toInt() and 0xff,
            opening = buf.get(at + 8).toInt() and 0xff,
            rated = (buf.get(at + 9).toInt() and 1) == 1,
            black = str(buf.getInt(at + 10)),
            white = str(buf.getInt(at + 14)),
            tournament = str(buf.getInt(at + 18)),
            round = str(buf.getInt(at + 22)),
            swap = str(buf.getInt(at + 26)),
            alt = str(buf.getInt(at + 30)),
            info = str(buf.getInt(at + 34)),
            blackCountry = str(buf.getInt(at + 38)),
            whiteCountry = str(buf.getInt(at + 42)),
            tourStart = str(buf.getInt(at + 46)),
            tourEnd = str(buf.getInt(at + 50)),
            tourCountry = str(buf.getInt(at + 54)),
            cells = (0 until nmoves).map { buf.get(at + 59 + it).toInt() and 0xff },
        )
    }

    /** RIF opening table (26 named openings) baked into the games pack. */
    fun openingName(oid: Int): Pair<String, String>? {
        if (oid <= 0 || openTblOff + 4 > buf.capacity()) return null
        val cnt = buf.getInt(openTblOff)
        for (i in 0 until cnt) {
            val e = openTblOff + 4 + 9 * i
            if (e + 9 > buf.capacity()) return null
            if ((buf.get(e).toInt() and 0xff) == oid) {
                return str(buf.getInt(e + 1)) to str(buf.getInt(e + 5))
            }
        }
        return null
    }

    /** RIF rule table (Classic / Soosyrv-8 / …). */
    fun ruleName(rid: Int): String? {
        if (rid <= 0 || ruleTblOff + 4 > buf.capacity()) return null
        val cnt = buf.getInt(ruleTblOff)
        for (i in 0 until cnt) {
            val e = ruleTblOff + 4 + 5 * i
            if (e + 5 > buf.capacity()) return null
            if ((buf.get(e).toInt() and 0xff) == rid) return str(buf.getInt(e + 1))
        }
        return null
    }

    /** NUL-terminated UTF-8 out of the shared pool; offset 0 is "?". */
    private fun str(off: Int): String {
        val start = poolOff.toLong() + (off.toLong() and 0xffffffffL)
        if (start < 0 || start >= buf.capacity()) return "?"
        var end = start.toInt()
        while (end < buf.capacity() && buf.get(end).toInt() != 0) end++
        val bytes = ByteArray(end - start.toInt())
        for (i in bytes.indices) bytes[i] = buf.get(start.toInt() + i)
        return String(bytes, Charsets.UTF_8)
    }

    private fun uLess(a: Int, b: Int): Boolean =
        (a.toLong() and 0xffffffffL) < (b.toLong() and 0xffffffffL)

    companion object {
        const val MAGIC = "RJG1"

        fun open(source: ByteBuffer): RjGamesPack? {
            val buf = source.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            if (buf.capacity() < 64) return null
            if (magic(buf) != MAGIC || buf.getInt(4) != 2) return null
            return RjGamesPack(buf)
        }
    }
}

private fun magic(buf: ByteBuffer): String =
    String(ByteArray(4) { buf.get(it) }, Charsets.US_ASCII)
